In [1]:
import numpy as np
import pandas as pd

## Load new_x

In [11]:
itr = 0
PW = np.load('../Data_peakwv/' + str(itr) + '/new_x.npy')
Euclidean = np.load('../Data_euclidean/' + str(itr) + '/new_x.npy')
AP = np.load('../Data_AP/' + str(itr) + '/new_x.npy')

## Load the best_estimate and append to new_x

In [3]:
PW_BE = np.load('../Data_peakwv/' + str(itr) + '/best_estimate.npy')
Euclidean_BE = np.load('../Data_euclidean/' + str(itr) + '/best_estimate.npy')
AP_BE = np.load('../Data_AP/' + str(itr) + '/best_estimate.npy')

In [4]:
PW = np.vstack((PW, PW_BE))
PW

array([[-1.95254081,  0.41252527],
       [-6.92655743,  1.08891464],
       [ 2.80679004,  1.61040092],
       [ 5.62589042,  3.38136773],
       [-1.39214835,  0.24254589]])

In [5]:
Euclidean = np.vstack((Euclidean, Euclidean_BE))
Euclidean

array([[-1.95254081,  0.41252527],
       [-6.92655743,  1.08891464],
       [ 2.80679004,  1.61040092],
       [ 5.62589042,  3.38136773],
       [-1.53583616,  0.23185006]])

In [6]:
AP = np.vstack((AP, AP_BE))
AP

array([[-1.95254081,  0.41252527],
       [-6.92655743,  1.08891464],
       [ 2.80679004,  1.61040092],
       [ 5.62589042,  3.38136773],
       [-1.4691689 ,  0.23993173]])

## Combine Everything into a DataFrame

In [8]:
#Target 
CTAB = np.array([416]*15).reshape(-1,1)
GC = np.array([256]*15).reshape(-1,1)
SEEDS = np.array([102]*15).reshape(-1,1)
data = np.vstack((PW, Euclidean, AP))
data = np.hstack((CTAB, GC, data[:,0].reshape(-1,1), data[:,1].reshape(-1,1), SEEDS))
water = (1300 - np.sum(data, axis=1)).reshape(-1,1)
data = np.hstack((CTAB.reshape(-1,1), water.reshape(-1,1), data[:,1:]))
data = np.round(data)
df = pd.DataFrame(data, columns = ['CTAB-stock','water-stock','GC-stock','AG-stock','AA-stock','SEEDS-stock'])

In [9]:
df.where(df > 20, 0, inplace=True)

In [10]:
df

CTAB-stock  water-stock  GC-stock  AG-stock  AA-stock  SEEDS-stock
0        416.0        528.0     256.0       0.0       0.0        102.0
1        416.0        532.0     256.0       0.0       0.0        102.0
2        416.0        522.0     256.0       0.0       0.0        102.0
3        416.0        517.0     256.0       0.0       0.0        102.0
4        416.0        527.0     256.0       0.0       0.0        102.0
5        416.0        528.0     256.0       0.0       0.0        102.0
6        416.0        532.0     256.0       0.0       0.0        102.0
7        416.0        522.0     256.0       0.0       0.0        102.0
8        416.0        517.0     256.0       0.0       0.0        102.0
9        416.0        527.0     256.0       0.0       0.0        102.0
10       416.0        528.0     256.0       0.0       0.0        102.0
11       416.0        532.0     256.0       0.0       0.0        102.0
12       416.0        522.0     256.0       0.0       0.0        102.0
13       416.0        517.0     256.0       0.0       0.0        102.0
14       416.0        527.0     256.0       0.0       0.0        102.0

In [106]:
#df = df[0:5]

In [107]:
#df2 = pd.DataFrame(np.array([488 ,416, 256, 0, 90, 102]).reshape(1,-1) , columns = ['water-stock','CTAB-stock','GC-stock','AG-stock','AA-stock','SEEDS-stock'])
#df = df.append(df2)

In [108]:
df

CTAB-stock  water-stock  GC-stock  AG-stock  AA-stock  SEEDS-stock
0        416.0        472.0     256.0      41.0       0.0        102.0
1        416.0        385.0     256.0      31.0     110.0        102.0
2        416.0        320.0     256.0      69.0     137.0        102.0
3        416.0        361.0     256.0      39.0     126.0        102.0
4        416.0        369.0     256.0      26.0     131.0        102.0
5        416.0        377.0     256.0      91.0      58.0        102.0
6        416.0        325.0     256.0     113.0      88.0        102.0
7        416.0        444.0     256.0      31.0      51.0        102.0
8        416.0        458.0     256.0      53.0       0.0        102.0
9        416.0        357.0     256.0      65.0     105.0        102.0
10       416.0        458.0     256.0       0.0      53.0        102.0
11       416.0        404.0     256.0      28.0      94.0        102.0
12       416.0        385.0     256.0       0.0     123.0        102.0
13       416.0        273.0     256.0     105.0     147.0        102.0
14       416.0        298.0     256.0     131.0      97.0        102.0

In [109]:
df.sum(axis=1)

0     1287.0
1     1300.0
2     1300.0
3     1300.0
4     1300.0
5     1300.0
6     1300.0
7     1300.0
8     1285.0
9     1301.0
10    1285.0
11    1300.0
12    1282.0
13    1299.0
14    1300.0
dtype: float64

In [110]:
df.sum(axis=0)

CTAB-stock     6240.0
water-stock    5686.0
GC-stock       3840.0
AG-stock        823.0
AA-stock       1320.0
SEEDS-stock    1530.0
dtype: float64

In [111]:
df.to_csv('Itr' + str(itr) + '.csv')