In [37]:
import numpy as np
import pandas as pd

## Load new_x

In [86]:
itr = 6
PW_SPHERE = np.load('../Data_peakwv_SPHERE/' + str(itr) + '/new_x.npy')
Euclidean_SPHERE = np.load('../Data_euclidean_SPHERE/' + str(itr) + '/new_x.npy')
AP_SPHERE = np.load('../Data_AP_SPHERE/' + str(itr) + '/new_x.npy')
SRVF_SPHERE = np.load('../Data_SRVF_SPHERE/' + str(itr) + '/new_x.npy')

PW_ROD = np.load('../Data_peakwv_ROD/' + str(itr) + '/new_x.npy')
Euclidean_ROD = np.load('../Data_euclidean_ROD/' + str(itr) + '/new_x.npy')
AP_ROD = np.load('../Data_AP_ROD/' + str(itr) + '/new_x.npy')
SRVF_ROD = np.load('../Data_SRVF_ROD/' + str(itr) + '/new_x.npy')

## Load the best_estimate and append to new_x

In [87]:
PW_BE_SPHERE = np.load('../Data_peakwv_SPHERE/' + str(itr) + '/best_estimate.npy')
Euclidean_BE_SPHERE = np.load('../Data_euclidean_SPHERE/' + str(itr) + '/best_estimate.npy')
AP_BE_SPHERE = np.load('../Data_AP_SPHERE/' + str(itr) + '/best_estimate.npy')
SRVF_BE_SPHERE = np.load('../Data_SRVF_SPHERE/' + str(itr) + '/best_estimate.npy')

PW_BE_ROD = np.load('../Data_peakwv_ROD/' + str(itr) + '/best_estimate.npy')
Euclidean_BE_ROD = np.load('../Data_euclidean_ROD/' + str(itr) + '/best_estimate.npy')
AP_BE_ROD = np.load('../Data_AP_ROD/' + str(itr) + '/best_estimate.npy')
SRVF_BE_ROD = np.load('../Data_SRVF_ROD/' + str(itr) + '/best_estimate.npy')

In [88]:
PW_ROD = np.vstack((PW_ROD, PW_BE_ROD))
PW_ROD

array([[ 83.42686604, 111.034132  ],
       [ 81.00096967,  97.70725112],
       [100.09690773, 120.22911911],
       [103.04464483, 102.19671137],
       [ 84.38925501, 110.54576215]])

In [89]:
Euclidean_ROD = np.vstack((Euclidean_ROD, Euclidean_BE_ROD))
Euclidean_ROD

array([[ 27.40006185,  51.73146852],
       [150.        ,  90.010548  ],
       [150.        ,  67.85080791],
       [150.        ,  79.36613487],
       [125.02582119,  84.05488838]])

In [90]:
SRVF_ROD = np.vstack((SRVF_ROD, SRVF_BE_ROD))
SRVF_ROD

array([[ 90.4640799 ,  95.01896567],
       [107.41237387, 102.66249249],
       [129.07379904,  75.91649337],
       [115.93607992,  88.90117731],
       [ 86.31820986,  95.44671369]])

In [91]:
AP_ROD = np.vstack((AP_ROD, AP_BE_ROD))
AP_ROD

array([[ 92.4545246 , 101.13015431],
       [ 94.76198687,  50.32452313],
       [ 15.37640806,  57.25719301],
       [ 10.14000001,  10.14000001],
       [121.2899922 ,  97.98226297]])

In [92]:
PW_SPHERE = np.vstack((PW_SPHERE, PW_BE_SPHERE))
PW_SPHERE

array([[ 80.26030911,  10.14000001],
       [121.03755575,  10.14000001],
       [ 79.24840646,  76.3255548 ],
       [ 85.09418191, 150.        ],
       [ 10.14000001, 125.40971642]])

In [93]:
Euclidean_SPHERE = np.vstack((Euclidean_SPHERE, Euclidean_BE_SPHERE))
Euclidean_SPHERE

array([[ 88.68329954, 150.        ],
       [ 10.14000001, 150.        ],
       [ 10.14000001,  80.18035186],
       [ 10.14000001, 117.56510989],
       [ 10.76580799, 127.30364441]])

In [94]:
SRVF_SPHERE = np.vstack((SRVF_SPHERE, SRVF_BE_SPHERE))
SRVF_SPHERE

array([[110.44366678,  65.93039804],
       [ 11.9307331 , 150.        ],
       [ 51.54989763,  10.14000001],
       [ 36.90460314, 117.4145524 ],
       [ 11.94236812, 150.        ]])

In [95]:
AP_SPHERE = np.vstack((AP_SPHERE, AP_BE_SPHERE))
AP_SPHERE

array([[ 98.9656945 , 112.96457456],
       [ 23.41453587,  69.00568044],
       [ 34.6175722 ,  36.72315823],
       [ 80.62278199,  79.89589665],
       [ 10.14000001, 133.4518421 ]])

## Combine Everything into a DataFrame

In [96]:
#Target 
CTAB = np.array([416]*40).reshape(-1,1)
GC = np.array([256]*40).reshape(-1,1)
SEEDS = np.array([102]*40).reshape(-1,1)
BLANK = np.array([0,0]).reshape(1,-1)
data = np.vstack((PW_ROD, Euclidean_ROD, SRVF_ROD, AP_ROD, PW_SPHERE, Euclidean_SPHERE, SRVF_SPHERE, AP_SPHERE))
data = np.hstack((CTAB, GC, data[:,0].reshape(-1,1), data[:,1].reshape(-1,1), SEEDS))
water = (1300 - np.sum(data, axis=1)).reshape(-1,1)
data = np.hstack((CTAB.reshape(-1,1), water.reshape(-1,1), data[:,1:]))
data = np.round(data)
df = pd.DataFrame(data, columns = ['CTAB-stock','water-stock','GC-stock','AG-stock','AA-stock','SEEDS-stock'])

In [97]:
df.where(df > 20, 0, inplace=True)

In [98]:
df

CTAB-stock  water-stock  GC-stock  AG-stock  AA-stock  SEEDS-stock
0        416.0        332.0     256.0      83.0     111.0        102.0
1        416.0        347.0     256.0      81.0      98.0        102.0
2        416.0        306.0     256.0     100.0     120.0        102.0
3        416.0        321.0     256.0     103.0     102.0        102.0
4        416.0        331.0     256.0      84.0     111.0        102.0
5        416.0        447.0     256.0      27.0      52.0        102.0
6        416.0        286.0     256.0     150.0      90.0        102.0
7        416.0        308.0     256.0     150.0      68.0        102.0
8        416.0        297.0     256.0     150.0      79.0        102.0
9        416.0        317.0     256.0     125.0      84.0        102.0
10       416.0        341.0     256.0      90.0      95.0        102.0
11       416.0        316.0     256.0     107.0     103.0        102.0
12       416.0        321.0     256.0     129.0      76.0        102.0
13       416.0        321.0     256.0     116.0      89.0        102.0
14       416.0        344.0     256.0      86.0      95.0        102.0
15       416.0        332.0     256.0      92.0     101.0        102.0
16       416.0        381.0     256.0      95.0      50.0        102.0
17       416.0        453.0     256.0       0.0      57.0        102.0
18       416.0        506.0     256.0       0.0       0.0        102.0
19       416.0        307.0     256.0     121.0      98.0        102.0
20       416.0        436.0     256.0      80.0       0.0        102.0
21       416.0        395.0     256.0     121.0       0.0        102.0
22       416.0        370.0     256.0      79.0      76.0        102.0
23       416.0        291.0     256.0      85.0     150.0        102.0
24       416.0        390.0     256.0       0.0     125.0        102.0
25       416.0        287.0     256.0      89.0     150.0        102.0
26       416.0        366.0     256.0       0.0     150.0        102.0
27       416.0        436.0     256.0       0.0      80.0        102.0
28       416.0        398.0     256.0       0.0     118.0        102.0
29       416.0        388.0     256.0       0.0     127.0        102.0
30       416.0        350.0     256.0     110.0      66.0        102.0
31       416.0        364.0     256.0       0.0     150.0        102.0
32       416.0        464.0     256.0      52.0       0.0        102.0
33       416.0        372.0     256.0      37.0     117.0        102.0
34       416.0        364.0     256.0       0.0     150.0        102.0
35       416.0        314.0     256.0      99.0     113.0        102.0
36       416.0        434.0     256.0      23.0      69.0        102.0
37       416.0        455.0     256.0      35.0      37.0        102.0
38       416.0        365.0     256.0      81.0      80.0        102.0
39       416.0        382.0     256.0       0.0     133.0        102.0

In [99]:
df.sum(axis=1)

0     1300.0
1     1300.0
2     1300.0
3     1300.0
4     1300.0
5     1300.0
6     1300.0
7     1300.0
8     1300.0
9     1300.0
10    1300.0
11    1300.0
12    1300.0
13    1300.0
14    1299.0
15    1299.0
16    1300.0
17    1284.0
18    1280.0
19    1300.0
20    1290.0
21    1290.0
22    1299.0
23    1300.0
24    1289.0
25    1300.0
26    1290.0
27    1290.0
28    1290.0
29    1289.0
30    1300.0
31    1288.0
32    1290.0
33    1300.0
34    1288.0
35    1300.0
36    1300.0
37    1301.0
38    1300.0
39    1289.0
dtype: float64

In [100]:
df.sum(axis=0)

CTAB-stock     16640.0
water-stock    14535.0
GC-stock       10240.0
AG-stock        2780.0
AA-stock        3570.0
SEEDS-stock     4080.0
dtype: float64

In [101]:
df.to_csv('Itr' + str(itr) + '.csv')